### ISSUE TITLE
make option to check in when you're already checked in

### ISSUE THREAD

**Issue by ArnaudWeyts** [punchtime/android#23]
This will implicitly check out and directly after check in in the new location.

Milestone: later xd

This will require a special kind of fab when you're already logged in.

**Comment by ArnaudWeyts** [comment]
What? I forgot what I meant by this

**Comment by Haroenv** [comment]
I wrote this. You should be able to check in a new location when you're already checked in somewhere.

This would be syntactic sugar over checking out and checkin in immediately
