### ISSUE TITLE
Toggle in toolbar

### ISSUE THREAD

**Issue by Haroenv** [punchtime/android#4]
There should be a toggle for manual mode in the toolbar like pinned emails in Google Inbox

**Comment by ArnaudWeyts** [comment]
added switchbutton, needs custom thumb icon

**Comment by Haroenv** [comment]
SO for the custom toggle: http://stackoverflow.com/questions/11499574/toggle-button-using-two-image-on-different-state

**Comment by Haroenv** [comment]
previous link seems useless after all. This seems more promising: https://android-arsenal.com/details/1/1985

reasons to use:
- seems to do what we want

reasons not to use:
- issues with cpu usage
- artificially high minimum api
- non-merged pull requests for almost a year
